---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk

inputs:
- name: galacticraft
- name: version

caches:
  - path: .gradle/

params:
  AWS_ACCESS_KEY_ID: "((aws-access-key-id))"
  AWS_SECRET_ACCESS_KEY: "((aws-secret-access-key))"

run:
  path: bash
  args: ["build.sh"]
  dir: galacticraft
